### ISSUE TITLE
Add processes and guide for projects using go mod

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-log#11]
In a project using go mod, cb-log library pkg is automatically generated on `$GOPATH/pkg/mod/cloud-barista/cb-log@v0.x.x`.

For this,  An appropriate method is needed. (not setting up `$GOPATH/src/github.com/cloud-barista/cb-log` as an environment variable.)

My suggestion: 
- A developer creates log_conf.yaml on his/her projects.
- cb-log can read that on setup. (Additional processes will be added.)

Finally, a guide about this will be added.

**Comment by powerkimhub** [comment]
~~cf) https://github.com/cloud-barista/cb-log/pull/12~~
cf) https://github.com/cloud-barista/cb-log/pull/13
cf) https://github.com/cloud-barista/cb-log/pull/15
