### ISSUE TITLE
[Suggestion] Add logging level (trace, fatal, panic)

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cb-log#16]
### [제안]
- 기존 "Logging level"에 "trace", "fatal", "panic" level 추가

### [효과]
- 로깅 레벨을 세분화하여 보다 편리한 프로그램 실행 또는 디버깅이 가능함
- 예) 
  - 프로그램 실행 시 Info level을 적용
  - 수행 과정의 문제 발생 시 Debug level 적용하여 디버깅함
  - 변수 값, 변수/함수 참조, 요청에 대한 응답 값 등의 확인이 필요한 경우 Trace level 적용하여 디버깅함
 
그 밖의 예제는 [여기](https://github.com/cb-contributhon/cb-coffeehouse/wiki/The-logging-level-to-understand-through-examples)를 참고 바랍니다.

### [TO-BE]
기존 "debug", "info", "warn", "error"의 변경 없이 "trace", "fatal", "panic"을 추가하는 것이기 때문에 기존 cb-log 사용자에게 영향을 주지 않을 것 입니다.
```go
func checkLevel(lvl string) error {
	switch strings.ToLower(lvl) {
	case "trace":
		return nil
	case "debug":
		return nil
	case "info":
		return nil
	case "warn", "warning":
		return nil
	case "error":
		return nil
	case "fatal":
		return nil
	case "panic":
		return nil
	}
	return fmt.Errorf("not a valid cblog Level: %q", lvl)
}
```

### [AS-IS]
```go
func checkLevel(lvl string) error {
	switch strings.ToLower(lvl) {
	case "error":
		return nil
	case "warn", "warning":
		return nil
	case "info":
		return nil
	case "debug":
		return nil
	}
	return fmt.Errorf("not a valid cblog Level: %q", lvl)
}
```

**Comment by powerkimhub** [comment]
@hermitkim1 Thanks for your Suggestion!

- 초기에 단순화를 위해 4가지로 filtering 했었는데, 제안 주신대로 log level을 전부 제공하는게 더 좋을 듯합니다.
- 다만, 이 경우에는 checkLevel() 함수을 수정하기보다는 그냥 삭제하는게 더 좋겠습니다. 
- cblogger.go:117Line에서 호출하는 아래 함수를 참고해 보시기바랍니다.
  - cf) https://github.com/sirupsen/logrus/blob/cd4bf4ef8de16b243cce0e062742feb34128648b/logrus.go#L25

 - 추가적으로, log level option 가이드를 동반 수정하면 좋을 듯합니다. 
   - cf)  https://github.com/cloud-barista/cb-log/blob/58e3a44dd81ce745268065da47710933c522aa8f/conf/log_conf.yaml#L7
   
- 며칠간 contribution하실 분을 기다려 보겠습니다^^
  - 혹시, PR 들어가실 분께서는 self assign 후 진행부탁드립니다.

**Comment by yunkon-kim** [comment]
저장소 쓰기 권한이 없어 Self-assign을 할 수 없습니다. :sob:

할당해 주시면 PR 올리겠습니다.

[참고]
> Anyone with write permissions to a repository can assign issues and pull requests. - [Assigning issues and pull requests to other GitHub users](https://docs.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)

![image](https://user-images.githubusercontent.com/7975459/105387010-72554380-5c58-11eb-8f29-bd9b48567195.png)

**Comment by powerkimhub** [comment]
@hermitkim1 

- CB-LOG Team 만들어서 추가해드렸습니다. 
- 다시한번해보세요~

**Comment by yunkon-kim** [comment]
@powerkimhub 
Assignees 조정 가능합니다. 조치해주셔서 감사드립니다.

**Comment by yunkon-kim** [comment]
@seokho-son 
Assign 해주셨네요 ㅎㅎ 감사합니다.
