### ISSUE TITLE
[v0.6.1] Overwrite logger Name and ...

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-log#27]
@yunkon-kim 

**[before v0.61]**
- GetLogger(loggerName)을 통해서 최초 호출시 Logger 생성 및 이후 호출시 동일한 Logger를 제공
- GetLogger() 최초 호출시 입력한 logger name으로 설정되며 이후 수정 불가능
- 참고: Logger Name과 Log 출력 예시: logger name이 `CLOUD-BARISTA`인 경우
  ```
  [CLOUD-BARISTA].[INFO]: 2022-08-24 00:31:53 nutsdb-driver.go:36, ......... 줄임
  ``` 
- 참고: 현재, 단일 logger를 제공하므로, cb-log를 포함한 실행 프로세스 당 1개의 logger만 운영 가능

**[since v0.6.1]**
- GetLogger(loggerName) 호출시  기존 Logger가 존재하면,
- 마지막 입력한 loggerName으로 기존 Logger의 이름을 변경할 수 있도록 개선

**[v0.6.1 이슈 현황]**
- Logger Header가 의도치 않게 계속 바뀜
- Hiscall이나 기존 사용 중인 프레임워크 중 Logger Header를 활용 중이라면, (활용 중인지는 미확인)
- 인지하지 못하는 문제를 발생시킬 수 있음
- Spider 예시
  - 기존 버전(cb-log v0.5.0) 활용시
    ```
    [CLOUD-BARISTA].[INFO]: 2022-08-24 00:31:53 nutsdb-driver.go:36, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.initialize() - ######## dbfile: /tmp/log-test/cb-spider/meta_db/dat
    
    ... 중략 ...
    
    [CLOUD-BARISTA].[INFO]: 2022-08-24 00:32:40 nutsdb-driver.go:160, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.(*NUTSDBDriver).GetList() - Key:/resource-info-spaces/iids/aws-ohio-config/vm/vm-01
    [CLOUD-BARISTA].[ERROR]: 2022-08-24 00:32:40 IIDManager.go:201, github.com/cloud-barista/cb-spider/cloud-control-manager/iid-manager.(*IIDRWLOCK).GetIID() - [aws-ohio-config:vm:vm-01] does not exist!
    [CLOUD-BARISTA].[ERROR]: 2022-08-24 00:32:40 CCMCommon.go:5790, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCSPResourceName() - [aws-ohio-config:vm:vm-01] does not exist!
    ```

  - 새버전(cb-log v0.6.1) 활용시
  - CLOUD-BARISTA => CB-SPIDER => CB-GRPC 
    ```
    [CLOUD-BARISTA].[INFO]: 2022-08-24 00:33:14 nutsdb-driver.go:36, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.initialize() - ######## dbfile: /tmp/mini/cb-spider/meta_db/dat
    
    ... 중략 ...
    
    [CB-SPIDER].[INFO]: 2022-08-24 00:33:17 nutsdb-driver.go:36, github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.initialize() - ######## dbfile: /tmp/mini/cb-spider/meta_db/dat
    [CB-SPIDER].[INFO]: 2022-08-24 00:33:20 CBSpiderRuntime.go:431, github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer() - **** Rest Auth Disabled ****
    
    ... 중략 ...
    
    [CB-GRPC].[ERROR]: 2022-08-24 00:33:29 CCMCommon.go:5832, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCSPResourceName() - [aws-ohio:vm:vm-01] does not exist!
    ```

**[관련 제안]**
- Multiple Logger를 제공하면, 좋겠지만...
- Logger Name 변경을 다음 링크와 같은 활용 목적이라면, 
  - https://github.com/cloud-barista/cb-larva/pull/324#issuecomment-1223735600
- `WithFields()` 활용으로 해결이 가능할지 확인 부탁 드립니다. 
  - 활용 예시
    ```
    cb-log# grep WithField test/test.go
    ```

**Comment by powerkimhub** [comment]
@yunkon-kim 

- Rollbacked in [v0.6.2](https://github.com/cloud-barista/cb-log/releases/tag/v0.6.2)
- 현재는 다른 방안을 모색해보시는 것이 좋을 듯하네요.

**Comment by yunkon-kim** [comment]
@powerkimhub 자세한 설명 및 제안사항을 알려주셔서 감사합니다!!

메시지 작성하고 있었는데 벌써 롤백을 하셨네요 ^^;;

작성하던 메시지는 메모 및 공유 차원에서 남겨 두도록 하겠습니다.

----

제 생각도 Multiple Logger를 제공하는 것이 장기적으로 보았을 때 좋을 것 같습니다.

하지만, 현 상황을 반영하는 것도 이에 못지 않게 중요하다고 생각합니다.

그래서 아래와 같이 세 가지 경우로 구분하여 설명을 남깁니다.

#### [Multiple logger 적용하는 경우]
1. Multiple logger를 개발, 적용, 테스트 및 배포를 수행합니다.
2. 각 프레임워크에서 이를 반영하면, **[v0.6.1 이슈 현황]과 유사한 로그를 출력**할 것 입니다. (단, logger별로 정리된 로그)
3. 따라서, **기존 로그 관련 소스코드를 분석하고, 관점별로 Logger를 구분하고, 이에 따라 수정 소요가 발생**합니다.

#### [WithFields()를 활용하는 경우]
1. **`v0.6.0`으로 롤백을 수행**합니다.
2. cb-network components의 **로그 관련 코드 전반을 수정하여 WithField()를 적용**합니다.
3. 분산 로깅 시스템에서 꼬리표처럼 WithField() 내용이 출력됩니다.
4. 기존 의도와 조금 다른 방향으로 **로그 메시지간 구분이 쉽지 않습니다.**

#### [v0.6.0을 활용하는 경우]
(말씀해주신 예시를 활용하여 설명 드립니다.)
1. Go package의 init() 순서에 따라 `nutsdb-driver`에서 **최초 Logger name (정확히는 LogFormat)을 설정 합니다.** (예, "CLOUD-BARISTA")
2. 그 이후 import된 package에서 init()을 수행하여 LogFormat을 수정을 시도합니다. (예, CB-SPIDER 또는 CB-GRPC)
3. 하지만, **이미 logger가 있는 경우로 수정되지 않습니다. (단순 Return)**
4. **이 경우, (main이 있는) 응용 프로그램의 대표 명칭으로 logger name을 설정하고자 할 때에도, 최초 설정한 Logger name을 변경할 수 없습니다.**
