### ISSUE TITLE
[Suggestion] relative path to absolute path && CBLOG_ROOT to include GOPATH

### ISSUE THREAD

**Issue by engineer-pjin** [cloud-barista/cb-log#5]
The relative path of readme.md is confusing to the user. For clarity, the absolute path looks good. 
And it is explained under the assumption that GOPTH is "~/go". I think this is also good to change to "$GOPATH".

**Comment by powerkimhub** [comment]
@engineer-pjin 
- Thanks for your suggestion.
- We will plan for it.

**Comment by engineer-pjin** [comment]
@powerkimhub 
May I PR proceed on this issue?

**Comment by powerkimhub** [comment]
@engineer-pjin Why not, thanks~

**Comment by engineer-pjin** [comment]
Thank you for your support. I will proceed with PR.

**Comment by engineer-pjin** [comment]
#6 PR progress completed.
