### ISSUE TITLE
cb-log 소스 코드 기반 실행 이슈

### ISSUE THREAD

**Issue by yoonjiOh** [cloud-barista/cb-log#9]
cb-log 를 소스 코드 기반에서 실행하기 위해 git clone 을 하고, test 파일을 돌려보던 중 아래와 같은 에러메세지가 나왔습니다. 

`go run sample.go
2020/10/13 22:42:13 error: open /src/github.com/cloud-barista/cb-log/conf/log_conf.yaml: no such file or directory
exit status 1`

sample.go 파일안의 
`import (
        “fmt”
        “time”
        “github.com/sirupsen/logrus”
        “github.com/cloud-barista/cb-log”
)`

이 부분이 문제가 되는 것 같은데요, 
소스 코드단에서 실행할 때도 go get github.com/cloud-barista/cb-log 를 실행해야 하는 것인가요? 

소스 코드 단에서 cb-spider 를 띄워놓고 cb-log 를 띄워놓고 연결할 수 있는 구조인 지도 궁금합니다. 
또한 이런 질문들을 issues 에 해도 되는 것일까요? 만일 적합하지 않다면 삭제하도록 하겠습니다.

**Comment by powerkimhub** [comment]
@yoonjiOh 
<문제분석>
- 현재 cb-log readme의 설치 가이드는 go module을 사용하지 않는 방법을 가이드하고 있습니다.
- 최신 go는 go module을 기본으로 사용하고 있습니다.  
- 아마도, 사용하시는 go 개발 환경은 module 기반인 거 같아요.
- 그래서, 다음 설정에서 $GOPATH가 빈문자열이어서(최신 go 설치시 $GOPATH를 사용하지 않는 것이 기본) $CBLOG_ROOT 설정이 잘못된 거 같아요.
  - `export CBLOG_ROOT=$GOPATH/src/github.com/cloud-barista/cb-log`
- 그래서, log_conf.yaml 파일을 못찾는 듯합니다. 

<확인방법>
  - 다음을 실행했을 때 파일이 보여야 함.
    - `ls $CBLOG_ROOT/conf/log_conf.yaml`

<해결방안>
- CBLOG_ROOT 재설정 후 시험
  (1) $GOPATH를 설정하거나, 
  (2) CBLOG_ROOT 설정에서 $GOPATH를 사용하지 않고 직접 경로를 입력 설정

<기타>
- 이슈로 올리셔도 되고,
- slack으로 문의 주셔도 됩니다^^

**Comment by powerkimhub** [comment]
@yoonjiOh 

- 문제가 해결되면 
  - 현재 이슈를 직접 close하시거나 
  - 답글을 남겨주세요.

**Comment by yoonjiOh** [comment]
문제 해결 완료. 테스트 성공. 

원인 
해당 에러는 go version 을 1.15 -> 1.14 로 바꿔도 동일하게 발생했었다. 
진짜 문제는 로컬에서 사용하는 shell 이 zsh 이었는데 가이드만 보고 .bashrc 에 GOPATH 를 설정한 것이었다. 
VM 으로 실습을 했을 때는 리눅스 기반이었기 때문에 bashrc 에 설정하는 것이 맞았으나 
로컬에서 소스 기반으로 실습할 때 내가 사용하고 있는 shell 을 먼저 체크했어야 했는데 이 부분을 아무 생각없이 적용하여 에러가 났었음. 

https://github.com/cloud-barista/cb-log/pull/10 에 리드미 수정 PR 을 올렸는데요, 
혹시 너무 기초적인 것이라면 approve 안 해주셔도 됩니다!

**Comment by yoonjiOh** [comment]
이 이슈는 해결되어 close 합니다.
